### ISSUE TITLE
删除文档出错

### ISSUE THREAD

**Issue by acracker** [zmister2016/MrDoc#45]
使用的mysql+pymysql

 ```2020-12-04 15:02:11.077 | ERROR    | app_doc.views:del_doc:1159 - 删除文档出错
Traceback (most recent call last):
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/django/db/backends/utils.py", line 84, in _execute
    return self.cursor.execute(sql, params)
           │    │      │       │    └ (3, '2020-12-04 15:02:11.076410', 1)
           │    │      │       └ 'UPDATE `app_doc_doc` SET `status` = %s, `modify_time` = %s WHERE `app_doc_doc`.`parent_doc` IN (SELECT U0.`id` FROM `app_doc...
           │    │      └ <function CursorWrapper.execute at 0x7f342ceee3b0>
           │    └ <django.db.backends.mysql.base.CursorWrapper object at 0x7f3421498c50>
           └ <django.db.backends.utils.CursorWrapper object at 0x7f3421498f90>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/django/db/backends/mysql/base.py", line 71, in execute
    return self.cursor.execute(query, args)
           │    │      │       │      └ (3, '2020-12-04 15:02:11.076410', 1)
           │    │      │       └ 'UPDATE `app_doc_doc` SET `status` = %s, `modify_time` = %s WHERE `app_doc_doc`.`parent_doc` IN (SELECT U0.`id` FROM `app_doc...
           │    │      └ <function Cursor.execute at 0x7f342dee15f0>
           │    └ <pymysql.cursors.Cursor object at 0x7f3421498d90>
           └ <django.db.backends.mysql.base.CursorWrapper object at 0x7f3421498c50>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/cursors.py", line 163, in execute
    result = self._query(query)
             │    │      └ "UPDATE `app_doc_doc` SET `status` = 3, `modify_time` = '2020-12-04 15:02:11.076410' WHERE `app_doc_doc`.`parent_doc` IN (SEL...
             │    └ <function Cursor._query at 0x7f342dee1a70>
             └ <pymysql.cursors.Cursor object at 0x7f3421498d90>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/cursors.py", line 321, in _query
    conn.query(q)
    │    │     └ "UPDATE `app_doc_doc` SET `status` = 3, `modify_time` = '2020-12-04 15:02:11.076410' WHERE `app_doc_doc`.`parent_doc` IN (SEL...
    │    │     └ "UPDATE `app_doc_doc` SET `status` = 3, `modify_time` = '2020-12-04 15:02:50.042289' WHERE `app_doc_doc`.`parent_doc` IN (SEL...
    │    └ <function Connection.query at 0x7f342de949e0>
    └ <pymysql.connections.Connection object at 0x7f34213e8810>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/connections.py", line 505, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
    │    │                │    │                             └ False
    │    │                │    └ <function Connection._read_query_result at 0x7f342de95050>
    │    │                └ <pymysql.connections.Connection object at 0x7f34213e8810>
    │    └ 0
    └ <pymysql.connections.Connection object at 0x7f34213e8810>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/connections.py", line 724, in _read_query_result
    result.read()
    │      └ <function MySQLResult.read at 0x7f342de95830>
    └ <pymysql.connections.MySQLResult object at 0x7f34214aa1d0>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/connections.py", line 1069, in read
    first_packet = self.connection._read_packet()
                   │    └ None
                   └ <pymysql.connections.MySQLResult object at 0x7f34214aa1d0>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/connections.py", line 676, in _read_packet
    packet.raise_for_error()
    │      └ <function MysqlPacket.raise_for_error at 0x7f342de8d440>
    └ <pymysql.protocol.MysqlPacket object at 0x7f34213c7f90>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/protocol.py", line 223, in raise_for_error
    err.raise_mysql_exception(self._data)
    │   │                     │    └ <member '_data' of 'MysqlPacket' objects>
    │   │                     └ <pymysql.protocol.MysqlPacket object at 0x7f34213c7f90>
    │   └ <function raise_mysql_exception at 0x7f342df13d40>
    └ <module 'pymysql.err' from '/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/err.py'>
  File "/opt/product/mrdoc_env/lib/python3.7/site-packages/pymysql/err.py", line 107, in raise_mysql_exception
    raise errorclass(errno, errval)
          │          │      └ "You can't specify target table 'app_doc_doc' for update in FROM clause"
          │          └ 1093
          └ <class 'pymysql.err.OperationalError'>

django.db.utils.OperationalError: (1093, "You can't specify target table 'app_doc_doc' for update in FROM clause")
```

**Comment by zmister2016** [comment]
1、Django官方推荐使用mysqlclient而非pymysql作为MySQL的连接库；
2、检查一下MySQL的版本，部分版本在Django2.2上有问题；
